FROM balenalib/%%RESIN_MACHINE_NAME%%-python

RUN apt-get update && apt-get install -y curl wget build-essential libelf-dev awscli
COPY . /usr/src/app
WORKDIR /usr/src/app

ENV VERSION '2.26.0+rev1.prod'
RUN ./build.sh %%RESIN_MACHINE_NAME%% $VERSION CH341SER_LINUX

CMD ./run.sh
