FROM balenalib/intel-nuc-debian:latest

RUN apt-get update && apt-get install -y curl wget build-essential libelf-dev awscli
COPY . /usr/src/app
WORKDIR /usr/src/app

ENV VERSION '2.29.0+rev1.prod'
RUN ./build.sh intel-nuc $VERSION CH341SER_LINUX

CMD ./run.sh

